# Generated by Django 4.0.5 on 2022-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
