# Generated by Django 4.0.5 on 2022-06-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_is_email_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_varified',
            new_name='is_email_verified',
        ),
    ]
