# Generated by Django 4.0.5 on 2022-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_is_email_varified_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='user/'),
        ),
    ]
