# Generated by Django 4.0.5 on 2022-07-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_student_name_remove_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='user/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='user/'),
        ),
    ]
