# Generated by Django 4.0.5 on 2022-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_name_student_photo_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to='images/user/'),
        ),
    ]
