# Generated by Django 4.0.5 on 2022-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_student_photo_alter_teacher_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile-icon.png', null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile-icon.png', null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile-icon.png', null=True, upload_to='images/user/'),
        ),
    ]
