# Generated by Django 4.0.5 on 2022-07-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='updated_at',
        ),
    ]
