# Generated by Django 4.0.5 on 2022-07-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
    ]
