# Generated by Django 4.0.5 on 2022-07-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20220707_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
