# Generated by Django 4.0.5 on 2022-08-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_student_photo_alter_teacher_photo_and_more'),
        ('classroom', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
