# Generated by Django 4.0.5 on 2022-08-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_assignment_due_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionassignment',
            old_name='Assignment',
            new_name='assignment',
        ),
    ]
