# Generated by Django 4.0.5 on 2022-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_mark',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submissionassignment',
            name='get_mark',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
