# Generated by Django 4.0.5 on 2022-08-16 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_assignment_total_mark_submissionassignment_get_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterials',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
