# Generated by Django 4.0.5 on 2022-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
