# Generated by Django 4.0.5 on 2022-08-18 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_discussion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 16, 23, 29, 453933)),
        ),
    ]
