# Generated by Django 4.0.5 on 2022-08-18 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_discussion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discussion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 19, 12, 49, 752097)),
        ),
    ]
