# Generated by Django 4.0.5 on 2022-08-18 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_alter_discussion_time_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionroom',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 6, 1, 223971)),
        ),
    ]
