# Generated by Django 4.0.5 on 2022-08-18 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_discussionroom_course_alter_discussion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 6, 29, 177861)),
        ),
    ]
