# Generated by Django 4.0.5 on 2022-08-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_alter_discussion_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
