# Generated by Django 4.0.5 on 2022-08-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_delete_discussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('time',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='time',
        ),
    ]
